# Generated by Django 2.1.7 on 2019-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('logo', models.ImageField(upload_to='images/logos')),
                ('web_address', models.URLField(blank=True)),
            ],
        ),
    ]
