# Generated by Django 2.1.7 on 2019-03-05 17:03

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('guitar_type', models.CharField(choices=[('Acoustic', 'Acoustic'), ('Electro-Acoustic', 'Electro-Acoustic'), ('Electric', 'Electric')], default='Acoustic', max_length=255)),
                ('djent', models.BooleanField(default=False)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='', verbose_name='upload_to=images/guitar_model/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitars.Brand')),
            ],
        ),
    ]
